- docs/Documentación/07-Registro-de-Cambios.mdx
- docs/Documentación/_category.json
- docs/Documentación/plantilla-registro-de-cambios.mdx
- yarn.lock
I have created a Documentation directory in Docusaurus. Created Changes log page and change template.
> Added documentation directory, and changes logs

- docs/Estimación de gastos e ingresos/Estimación de gastos e ingresos.md
- docs/Estimación de gastos e ingresos/_category_.json
I have created a new document in which the expenditures and incomes are estimated for the next 5 years.
> doc: Added estimated expenditure and income #96

- docs/Seguimiento del equipo/Prácticas recomendadas.mdx
I have created a new section on best practices for groups.
> doc: Create Team Practices section

- docs/Uso de IA/Detalles/2024-02-26_AlvaroG.md
- docs/Uso de IA/Detalles/2024-02-29_Javier.md
- docs/Uso de IA/Registro de uso de IA Semana 4.md
- docs/Uso de IA/Registro de uso de IA Semana 5.md
I have updated the AI usage for week 5.
> doc: AI usage week 5

- docs/Aportación a BGCC.md
- docs/Aportación a BGCC/Semana 1.md
- docs/Aportación a BGCC/Semana 2.md
- docs/Aportación a BGCC/Semana 3.md
- docs/Aportación a BGCC/Semana 4.md
I have updated the "Aportación a la BGCC" to the current date.
> doc: Update section

- docs/Seguimiento del equipo/Medición del rendimiento.mdx
I have included a section that provides for members to voluntarily change roles if necessary.
> doc: Update individual performance evaluation

- docs/Seguimiento del equipo/Acuerdo de compromiso.mdx
The CA has been updated to version 4.0 which includes a section focused on compliance with team practices as well as improving the compliance tables of the agreement as recommended in the feedback of the retrospective.
> doc: Update CA and improve compliance charts

- docs/Aportación a BGCC/Semana 3.md
- docs/Aportación a BGCC/Semana 4.md
- docs/Aportación a BGCC/Semana 5.md
- docs/Aportación a BGCC/Semana 6.md
- docs/Aportación a BGCC/Semana 7.md
I have updated the BGCC contribution section.
> doc:Update KB #178

- docs/Portada/Plantilla de la Portada.mdx
The cover page has been added as indicated in the failure conditions.
> doc: Add frontpage to docusaurus #222

- docs/Registro de problemas/Problemas encontrados.mdx
Please include a summary of the changes and the related issue. Please also include relevant motivation and context.
> doc: Added metric for the quality of the solution

- docs/Gestion de Usuarios Piloto/Software Reviewer Guideline - Sprint 2.mdx
Changed software reviewer credentials
> fix: User manual credentials

- src/pages/index.js
- yarn.lock
> doc: Delivery documents

- docs/03. Planificación/3.5. Replanificación.mdx
Updating the Sprint 3 with the latest changes and the PPL planning so it shows the current information we have.
> doc: Update S3 and PPL planning #286

- docs/Anexo I. Aportación a la BGCC/Semana 8.md
Week 8 feedback has been added
> doc:BGCC Week 9 feedback

- docs/03. Planificación/3.9. Briefing.mdx
This pr introduces the briefing document
> doc: Created the briefing for our company

- docs/Anexo I. Aportación a la BGCC/Semana 9.md
> doc: Add W9 feedback

- docs/02. Acuerdos y contratos/2.1. Acuerdo de compromiso.mdx
- yarn.lock
Modifyng the CA with week 10 data.
> doc: Update CA week 10

- docs/07. Manuales de usuario/7.3. Software Reviewer Guideline - Sprint 3.mdx
> fix: Limitations

- docs/05. Rendimiento/5.3. PerformanceEvaluation.mdx
> doc: Add S3 agreed perf. evaluation

- docs/Entrega.md
> doc: Update delivery section

- .gitattributes
- docs/07. Manuales de usuario/7.4. Manuales de Uso.mdx
- static/vid/Demo ACAT manual de uso .mp4
- static/vid/Demo CyC manual de uso.mp4
Added both videos for the user manual as the teacher suggested.
They can be watched in the sections Manuales de Usuario > Manuales de uso ACAT y CyC.
> doc: user manual videos and lfs filter

- docs/07. Manuales de usuario/7.4. Manuales de Uso.mdx
Added youtube iframes for user manuals.
> doc: add youtube videos iframes

- docs/06. Recursos/6.1. Presentaciones/6.1.8. 07-05-2024.md
I just created a mini story based on Cirio y Costal situation and tried to make it as real as possible, so people will engaged with the story in a few seconds.
> doc: Create the story of the PPL #381

- docs/03. Planificación/Modelo de negocio.mdx
calculated ROI for the business model
> doc: calculated ROI for the business model

- docs/06. Recursos/6.6. Trabajo futuro.mdx
A new future work section has been added to the documentation. In this section are explained all the future work to do in next courses.
> doc: Future work section

- docs/Anexo II. Uso de la IA/Registro de uso de IA Semana 11.md
- docs/Anexo II. Uso de la IA/Registro de uso de IA Semana 12.md
> doc: updated use of AI in PPL

- docs/05. Rendimiento/5.4. PilotUsersPerformanceEvaluation.mdx
Update pilot user perf. evaluation
> Update 5.4. PilotUsersPerformanceEvaluation.mdx

- docs/03. Planificación/3.11. Campaña de lanzamiento.mdx
The new launch campaign section has been added.
> Added launch campaign section #422

- docs/Anexo I. Aportación a la BGCC/Semana 12.md
Week 12 feedback added 🤓​☝️​
- [ X] I have performed a self-review of my code running `npm run build` and `npm run serve` after pushing the code.
- [X  ] I have checked that there is no fragile information published unintentionally.
> doc:Add week 12 feedback

- docs/03. Planificación/3.3. Marketing/3.11. Campaña de lanzamiento.mdx
Update some important information about PPL.
> Update Marketing doc

- docs/03. Planificación/3.10. Trabajo futuro.mdx
The future work section has been updated.
> doc: Update future work section

- docs/02. Acuerdos y contratos/2.1. Acuerdo de compromiso.mdx
> doc: update CA WPL

- docs/05. Rendimiento/5.3. PerformanceEvaluation.mdx
Updated the performance evaluation for the WPL
> doc: update performance for WPL

- docs/06. Recursos/6.6. Vídeos/Anuncio para inversores.md
- docs/06. Recursos/6.6. Vídeos/Anuncio usuarios.md
- docs/06. Recursos/6.6. Vídeos/Demo Cirio y Costal.md
- docs/06. Recursos/6.6. Vídeos/_category_.json
Added a new section under "Recursos" where I placed the videos we created for Harmony
> doc: Add Harmony videos #492
